"""empty message

Revision ID: 434ef777d4ae
Revises: 
Create Date: 2018-03-24 22:46:15.989612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434ef777d4ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fki_scholar_name', table_name='deroos')
    op.add_column('scholars', sa.Column('creation_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.alter_column('scholars', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('scholars', 'website',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scholars', 'website',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('scholars', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('scholars', 'creation_time')
    op.create_index('fki_scholar_name', 'deroos', ['scholar_name'], unique=False)
    # ### end Alembic commands ###
